src/carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done,
)


app_name = "cart"

urlpatterns = [
    path("", cart_home, name="home"),
    path("update", cart_update, name="update"),
    path("checkout", checkout_home, name="checkout"),
    path("checkout/success", checkout_done, name="success")
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from accounts.views import (
    login_page,
    register_page,
    guest_register_view,
)

from addresses.views import (
    checkout_address_create_view,
    checkout_address_reuse_view,
)

from billing.views import (
    payment_method_view,
    payment_method_create_view,
)

from carts.views import cart_detail_api_view

from .views import (
    home_page,
    about_page,
    contact_page,
)


urlpatterns = [
    path("", home_page, name="home"),
    path("about/", about_page, name="about"),
    path("api/cart/", cart_detail_api_view, name="api-cart"),
    path("billing/payment-method/", payment_method_view, name="billing-payment-method"),
    path("billing/payment-method/create", payment_method_create_view, name="billing-payment-method-endpoint"),
    path("cart/", include("carts.urls")),
    path("contact/", contact_page, name="contact"),
    path("checkout/address/create", checkout_address_create_view, name="checkout_address_create"),
    path("checkout/address/reuse", checkout_address_reuse_view, name="checkout_address_reuse"),
    path("register/", register_page, name="register"),
    path("register/guest/", guest_register_view, name="guest_register"),
    path("login/", login_page, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("products/", include("products.urls")),
    path("search/", include("search.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings
                                       .STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings
                                       .MEDIA_ROOT)

src/products/urls.py
from django.urls import path

from .views import (
    product_list_view,
    product_detail_slug_view
)


app_name = "products"

urlpatterns = [
    path("", product_list_view, name="list"),
    path("<str:slug>/", product_detail_slug_view, name="detail"),
]

src/templates/base/css.html
{% load static %}
<link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
    />
<link rel="stylesheet" href="{% static 'css/main.css'%}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

src/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"
></script>

<script src="https://js.stripe.com/v3/"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.7/jsrender.min.js" integrity="sha512-Y6fnBD9Z/4xDuDemzJBaYAQBGD/EOuaonQDW4W3Khf9j6gbvFd+K48MCW9UeMZrs5F/hELIuy7Mjpf/Ss4tRxQ==" crossorigin="anonymous"></script>

{% include 'base/js_templates.html '%}

<script src="{% static 'js/csrf.ajax.js' %}"></script>
<script src="{% static 'js/ecommerce.js' %}"></script>
<script src="{% static 'js/ecommerce.main.js' %}"></script>

src/templates/base/js_templates.html
{% verbatim %}
<script id="stripeTemplate" type="text/x-jsrender">
    <form class="payment-form" action="" method="post"
          id="payment-form" data-token="{{:publishKey}}"
          data-next-url="{{:nextUrl}}">
        <div class="form-row">
            <label for="card-element">
                Credit or debit card
            </label>
            <div id="card-element" class="form-control">
                <!-- A Stripe Element will be inserted here. -->
            </div>
            
            <!-- Used to display Element errors. -->
            <div id="card-errors" role="alert"></div>
        </div>
        
        <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
    </form>
</script>
{% endverbatim %}

src/templates/base/navbar.html
{% url "home" as home_url %}
{% url "contact" as contact_url %}
{% url "products:list" as products_url %}
{% url "login" as login_url %}
{% url "logout" as logout_url %}
{% url "register" as register_url %}
{% url "cart:home" as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">
            {% if brand_name %} 
                {{ brand_name }}
            {% else %}
                CFE eCommerce
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == products_url %} active {% endif %}">
                    <a class="nav-link" href="{{ products_url }}">Products</a>
                </li>

                {% if request.user.is_authenticated %}

                    <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                        <a class="nav-link" href="{{ logout_url }}">Logout</a>
                    </li>

                {% else %}

                    <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Register</a>
                    </li>
                    <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>

                {% endif %}

                <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
                    <a class="nav-link" href="{{ cart_url }}">
                        <span class="navbar-cart-count">    
                            {% if request.session.cart_items_count %}
                                {{ request.session.cart_items_count }} 
                            {% endif %}
                        </span>
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                </li>

            </ul>
            {% include "search/snippets/search-form.html" %}
        </div>
    </div>
</nav>