src/carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done,
)


app_name = "cart"

urlpatterns = [
    path("", cart_home, name="home"),
    path("update", cart_update, name="update"),
    path("checkout", checkout_home, name="checkout"),
    path("checkout/success", checkout_done, name="success")
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from accounts.views import (
    login_page,
    register_page,
    guest_register_view,
)

from addresses.views import (
    checkout_address_create_view,
    checkout_address_reuse_view,
)

from billing.views import (
    payment_method_view,
    payment_method_create_view,
)

from carts.views import cart_detail_api_view

from .views import (
    home_page,
    about_page,
    contact_page,
)


urlpatterns = [
    path("", home_page, name="home"),
    path("about/", about_page, name="about"),
    path("api/cart/", cart_detail_api_view, name="api-cart"),
    path("billing/payment-method/", payment_method_view, name="billing-payment-method"),
    path("billing/payment-method/create", payment_method_create_view, name="billing-payment-method-endpoint"),
    path("cart/", include("carts.urls")),
    path("contact/", contact_page, name="contact"),
    path("checkout/address/create", checkout_address_create_view, name="checkout_address_create"),
    path("checkout/address/reuse", checkout_address_reuse_view, name="checkout_address_reuse"),
    path("register/", register_page, name="register"),
    path("register/guest/", guest_register_view, name="guest_register"),
    path("login/", login_page, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("products/", include("products.urls")),
    path("search/", include("search.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings
                                       .STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings
                                       .MEDIA_ROOT)

src/carts/models.py
from django.conf import settings
from django.db import models
from django.db.models import QuerySet

from django.db.models.signals import pre_save, post_save, m2m_changed

from typing import Union

from products.models import Product


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, user:User, cart_id: Union[int, None]=None):
        # No user no cart_id -> new cart
        # No user cart_id -> cart by cart_id or new cart
        # User no cart_id -> cart by user or new cart
        # User cart_id -> cart by cart_id or cart by user or new cart

        cart = None
        if not user.is_authenticated:
            cart_by_user_qs = self.get_queryset().none()
        else:
            cart_by_user_qs = self.get_queryset().filter(user=user, active=True)

        cart_by_id_qs = self.get_queryset().filter(id=cart_id, active=True)

        print("\n\n CartManager")
        print(f"cart_id-{cart_id}")
        print(f"user-{user}")
        print(f"cart_by_id_qs-{cart_by_id_qs}")
        print(f"cart_by_user_qs-{cart_by_user_qs}")

        print("\n\n Actions")
        if cart_by_id_qs.exists() and cart_by_user_qs.exists():
            cart_by_id = cart_by_id_qs.last()
            print("get cart_by_id")
            if cart_by_id_qs.last() != cart_by_user_qs.last():
                cart_by_user = cart_by_user_qs.last()
                print("get cart_by_user")
                if cart_by_id.products.all().count() == 0:
                    cart_by_id.delete()
                    print("delete cart_by_id")
                    cart = cart_by_user
                    print("cart_by_user is winner")
                else:
                    cart_by_user = cart_by_user_qs.last()
                    cart_by_user.delete()
                    print("delete cart_by_user")
                    cart = cart_by_id
                    print("cart_by_id is winner")
            else:
                cart = cart_by_id
                print("cart_by_id is winner")

        elif cart_by_user_qs.exists():
            cart = cart_by_user_qs.last()
            print("cart_by_user is winner")
        elif cart_by_id_qs.exists():
            cart_by_id = cart_by_id_qs.last()
            print('get cart_by_id')
            if user.is_authenticated and cart_by_id.user is None:
                cart_by_id.user = user
                print("set new user to cart_by_id")
                print(f"user{cart_by_id.user}")
                cart_by_id.save()
            cart = cart_by_id
            print("cart_by_id is winner")
        else:
            cart = self.new(user=user)
            print('created new cart')
        return cart

    def new(self, user=None):
        user_obj = user if user is not None and user.is_authenticated else None
        return self.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if "post_" in action:
        products = instance.products.all()
        total = 0
        for p in products:
            total += p.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
            print("m2m change")


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    instance.total = float(instance.subtotal) * 0.99


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.services import (
    get_addresses_by_billing_profile,
    devide_addresses_on_shipping_and_billing,
)
from billing.models import BillingProfile
from billing.services import (
    load_billing_profile,
    has_associated_card,
)
from orders.models import Order
from orders.services import load_order
from products.models import Product
from .models import Cart
from .services import (
    get_cart_and_update_session_data,
    update_cart_and_session_data,
    do_checkout,
)

import stripe


STRIPE_SECRET_KEY = getattr(
    settings,
    "STRIPE_SECRET_KEY", 
    "sk_test_51HM8xIJWpkfHiKdZvgmZL84WTT571TOqAYHBN8xa9bp3kbv7XPKdjOJrfFFB4fJLx3SnUntrn5gAzQXaLuYjPY7g00n24pSpRM"
)
STRIPE_PUB_KEY = getattr(
    settings,
    "STRIPE_PUB_KEY",
    "pk_test_51HM8xIJWpkfHiKdZEUZVRXvZ2s7OP436CgUBwWquikW7fM73zwcwzEJkNcapaluBP6nEQ2LeHNMhGldmbpm405G300qiWFX2cN"
)
stripe.api_key = STRIPE_SECRET_KEY


def cart_detail_api_view(request):
    cart = get_cart_and_update_session_data(request)
    products = [{
        "id": p.id,
        "url": p.get_absolute_url(),
        "name": p.title,
        "price": p.price
        } for p in cart.products.all()
    ]
    cart_data = {
        "products": products,
        "subtotal": cart.subtotal,
        "total": cart.total,
    }
    return JsonResponse(cart_data)


def cart_home(request):
    cart = get_cart_and_update_session_data(request)
    print("\n\n cart_home")
    print(f"cart.id - {cart.id}")
    context = {
        "cart": cart,
    }
    return render(request, "carts/home.html", context)


def cart_update(request):
    if request.POST:
        product_id = request.POST.get("product_id")
        cart, product_added = update_cart_and_session_data(request, product_id=product_id)  
        if request.is_ajax():
            print("\n\nAJAX REQUEST\n\n")
            json_data = {
                "added": product_added,
                "removed": not product_added,
                "cartItemCount": cart.products.count(),
            }
            return JsonResponse(json_data)
    return redirect("cart:home") 


def checkout_home(request):
    cart = get_cart_and_update_session_data(request)
    if cart.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()

    billing_profile = load_billing_profile(request)
    has_card = has_associated_card(billing_profile=billing_profile)
    order = load_order(billing_profile=billing_profile, cart=cart)
    addresses = get_addresses_by_billing_profile(billing_profile=billing_profile)
    shipping_addresses, billing_addresses = devide_addresses_on_shipping_and_billing(
        addresses=addresses
    )

    print("checkout home")
    print(f"order-{order}")
    print(f"addresses-{addresses}")
    print(f"shipping_addresses-{shipping_addresses}")
    print(f"billing_addresses-{billing_addresses}")

    if request.method == "POST":
        success = do_checkout(request, order=order)
        if success:
            return redirect("cart:success")
        else:
            return redirect("card:checkout")

    context = {
        "order": order,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        'billing_profile': billing_profile,
        "shipping_addresses": shipping_addresses,
        "billing_addresses": billing_addresses,
        "has_card": has_card,
        "publish_key": STRIPE_PUB_KEY,
    }
    return render(request, 'carts/checkout.html', context)


def checkout_done(request):
    return render(request, 'carts/checkout-done.html', {})

src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %}

{% block content %}

<div class="col-6 mx-auto py-5 text-center">
    <h1 class="display-1">Thank you for your order!</h1>
</div>

{% endblock %}

src/carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}

{% if not billing_profile %}
    <div class="row text-center">
        <div class="col-12 col-md-6">
            <p class="lead">Login</p>
            {% include 'accounts/snippets/login_form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-6">
            Continue as Guest
            {% url "guest_register" as guest_register_url %}
            {% include 'accounts/snippets/login_form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>
{% else %}
    {% if not order.shipping_address %}
        <div class="row">
            <div class="col-md-8 mx-auto col-10">
                <p class="lead">Shipping Address</p>
                <hr>

                <div class="row">
                    <div class="col-6">
                        {% url "checkout_address_create" as checkout_address_create %}
                        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
                    </div>
                    <div class="col-6">
                        {% url "checkout_address_reuse" as checkout_address_reuse %}
                        {% include "addresses/previous_addresses.html" with addresses=shipping_addresses next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
                    </div>
                </div>
            </div>
        </div>
    {% elif not order.billing_address %}
        <div class="row">
            <div class="col-md-6 mx-auto col-10">
                <p class="lead">Billing Address</p>
                <hr>

                <div class="row">
                    <div class="col-6">
                        {% url "checkout_address_create" as checkout_address_create %}
                        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
                    </div>
                    <div class="col-6">
                        {% url "checkout_address_reuse" as checkout_address_reuse %}
                        {% include "addresses/previous_addresses.html" with addresses=billing_addresses next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        {% if not has_card %}
            <div class="stripe-payment-form"  data-token="{{ publish_key }}"
            data-next-url="{{ request.build_absolute_uri }}" data-btn-title="Add Payment Method">
        </div>
        {% else %}
            <h1>Finalize Checkout</h1> 
            <p>
                Cart Items: 
                {% for product in order.cart.products.all %}
                    {{ product }}
                    {% if not forloop.last %}
                        , 
                    {% endif %}
                {% endfor %}
            </p>
            <p>Shipping Address: {{ order.shipping_address.get_address }}</p>
            <p>Billing Address: {{ order.billing_address.get_address }}</p>
            <p>
                Payment Method: {{ billing_profile.default_card }} (
                    <a href="{{ billing_profile.get_payment_method_url }}?next={{ request.build_absolute_uri }}">Change</a>
                )
            </p>
            <p>Cart Total: {{ order.cart.total }}</p>
            <p>Shipping Total: {{ order.shipping_total }}</p>
            <p>Order Total: {{ order.total }}</p>

            <form action="" method="POST"> {% csrf_token %}
                <button class="btn btn-success" type="submit">Checkout</button>
            </form>
        {% endif %}
    {% endif %}
{% endif %}

{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}

{% if cart.products.exists %}

    <table class="table cart-table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Product price</th>
            </tr>
        </thead>
        <tbody class="cart-body">
            {% for product in cart.products.all %}
            <tr class="cart-product">
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                    {% include 'carts/snippets/remove-product.html' with product_id=product.id %}
                </td>
                <td>{{ product.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>
                    <b>Subtotal:</b>
                     $<span class="cart-subtotal">{{ cart.subtotal }}</span>
                </td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td>
                    <b>Total:</b>
                     $<span class="cart-total">{{ cart.total }}</span>
                </td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
            </tr>
        </tbody>
    </table>

    <div class="cart-item-remove-form" style="display:none;">
        {% include 'carts/snippets/remove-product.html' %}
    </div>

{% else %}

<p class="lead">Cart is empty!</p>

{% endif %}

{% endblock %}